import { FreeAI } from './free-ai.js';
import { weeklyReport, monitorReport } from './local-analysis.js';
const freeAI=new FreeAI();
let cancelRequest=null;
const $ = id => document.getElementById(id);
const today = () => { const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const read = (k,f) => {try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
const state={workouts:read('athWorkouts',[]),checkins:read('athCheckins',{}),pbs:read('athPbs',{}),events:read('athEvents',[]),profile:read('athProfile',{}),goals:read('athGoals','')};
const keys={workouts:'athWorkouts',checkins:'athCheckins',pbs:'athPbs',events:'athEvents',profile:'athProfile',goals:'athGoals'};
let toastTimer, busy=false, history=[], photo=null, previewURL=null;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function persist(){try{for(const [k,key] of Object.entries(keys))localStorage.setItem(key,JSON.stringify(state[k]));return true;}catch{toast('저장 공간이 부족합니다. 데이터를 백업해 주세요.');return false;}}
function fmtTime(s){if(!Number.isFinite(s))return '—';const n=Math.round(s*10);return Math.floor(n/600)+':'+((n%600)/10).toFixed(1).padStart(4,'0');}
function cutoff(days){const d=new Date(today()+'T12:00:00');d.setDate(d.getDate()-days+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s+'T12:00:00'));}
function dday(date){const n=Math.round((Date.parse(date+'T12:00:00')-Date.parse(today()+'T12:00:00'))/86400000);return n===0?'D-DAY':n>0?'D−'+n:'D+'+(-n);}
function getContext(){const t=today(),start7=cutoff(7),start28=cutoff(28);const select=start=>state.workouts.filter(x=>x.date>=start&&x.date<=t);return {asOf:t,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,profile:state.profile,pbs:state.pbs,recent7Days:select(start7),recent28Days:select(start28),checkins:Object.entries(state.checkins).filter(([date])=>date>=start28&&date<=t).map(([date,value])=>({date,...value})),competitions:state.events,goals:state.goals};}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('on',p.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.page===id));window.scrollTo(0,0);renderContext();}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function numberField(id,label,min,max,step='1',required=true){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');Object.assign(input,{id,type:'number',min:String(min),step,required});if(max!==null)input.max=String(max);input.inputMode=step==='1'?'numeric':'decimal';l.append(input);return l;}
function timeFields(prefix,parent){parent.append(numberField(prefix+'Min','분',0,9999),numberField(prefix+'Sec','초',0,59.9,'0.1'));}
function seconds(prefix){return Number($(prefix+'Min').value)*60+Number($(prefix+'Sec').value);}
function setTime(prefix,value){$(prefix+'Min').value=Math.floor(value/60);$(prefix+'Sec').value=+(value%60).toFixed(1);}
const fields={ '에르고':[['distance','거리 (m)',1,100000],['stroke','평균 피치 (선택)',1,60,'1',false]],'수상':[['distance','거리 (km)',0.01,300,'0.01'],['minutes','운동 시간 (분)',0.1,1440,'0.1'],['stroke','평균 피치 (선택)',1,60,'1',false]],'러닝':[['distance','거리 (km)',0.01,300,'0.01']],'웨이트':[['weight','중량 (kg)',0,600,'0.5'],['sets','세트',1,100],['reps','반복 횟수',1,200],['minutes','운동 시간 (분)',1,600]] };
function renderFields(){const parent=$('fields'),type=$('type').value;parent.replaceChildren();if(type==='웨이트'){const l=document.createElement('label');l.textContent='운동 이름';const i=document.createElement('input');Object.assign(i,{id:'f_exercise',required:true,maxLength:60,placeholder:'예: 스쿼트'});l.append(i);parent.append(l);}for(const [id,label,min,max,step,required] of fields[type])parent.append(numberField('f_'+id,label,min,max,step,required));if(['에르고','러닝'].includes(type))timeFields('f_',parent);}
function pbFields(){const p=$('pbFields');p.replaceChildren();p.className='grid';if($('pbType').value==='erg30')p.append(numberField('pbMeters','30분 거리 (m)',1,20000));else timeFields('pb',p);}
const pbLabels={erg2000:'에르고 2,000m',erg5000:'에르고 5,000m',erg30:'에르고 30분',run5000:'러닝 5km',run8000:'러닝 8km'};
function row(parent,title,detail,actions=[]){const r=document.createElement('div');r.className='row';const text=document.createElement('div');text.className='row-title';text.textContent=title;const small=document.createElement('small');small.textContent=detail;text.append(small);r.append(text);if(actions.length){const a=document.createElement('div');a.className='actions';for(const [label,fn] of actions){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;a.append(b);}r.append(a);}parent.append(r);}
function workoutText(x){if(x.legacy)return x.legacy;if(x.type==='웨이트')return `${x.exercise} · ${x.weight}kg · ${x.sets}×${x.reps}`;return `${x.distance||0}${x.type==='에르고'?'m':'km'} · ${x.time?fmtTime(x.time):x.minutes+'분'}${x.stroke?' · '+x.stroke+'spm':''}`;}
function duration(x){return x.minutes||((x.time||0)/60);}
function renderContext(){const c=getContext();$('contextSummary').textContent=`${c.profile.name||'프로필 미등록'} · 최근 7일 ${c.recent7Days.length}회 / 28일 ${c.recent28Days.length}회 · 체크인 ${c.checkins.length}일`;$('contextPreview').textContent=JSON.stringify(c,null,2);}
function render(){const t=today(),c=state.checkins[t];$('greeting').textContent=state.profile.name?`${state.profile.name}, 오늘도 한 스트로크 더.`:'오늘도, 한 스트로크 더.';$('homeCondition').textContent=c?.condition??'—';$('condition').value=c?.condition??7;$('conditionOut').textContent=$('condition').value;$('sleep').value=c?.sleep??'';$('fatigue').value=c?.fatigue??5;$('checkNote').value=c?.note??'';$('homePb').textContent=fmtTime(state.pbs.erg2000?.seconds);const upcoming=state.events.filter(x=>x.date>=t).sort((a,b)=>a.date.localeCompare(b.date));$('homeDday').textContent=upcoming.length?dday(upcoming[0].date):'READY?';$('homeEvent').textContent=upcoming[0]?.name||'다음 목표를 설정하세요';$('raceDate').textContent=upcoming.length?`${upcoming[0].date} · ${upcoming[0].boat||'종목 미등록'} · ${upcoming[0].goal||'목표를 등록하세요'}`:'대회 날짜와 목표를 등록해 보세요.';const week=getContext().recent7Days;$('weekCount').textContent=week.length+'회';const load=week.reduce((sum,x)=>sum+duration(x)*Number(x.rpe||0),0);$('weekStats').textContent=`최근 7일 ${week.length}회 · ${Math.round(week.reduce((s,x)=>s+duration(x),0))}분 · 부하 ${Math.round(load)}`;const loads=Array.from({length:28},(_,i)=>{const date=cutoff(28-i);return state.workouts.filter(x=>x.date===date).reduce((s,x)=>s+duration(x)*Number(x.rpe||0),0);});$('loadChart').replaceChildren();const max=Math.max(...loads,1);loads.forEach((v,i)=>{const b=document.createElement('div');b.className='bar'+(i>=21?' recent':'');b.style.height=Math.max(3,v/max*100)+'%';b.title=cutoff(28-i)+': '+Math.round(v);$('loadChart').append(b);});$('workouts').replaceChildren();const records=state.workouts.filter(x=>$('filter').value==='전체'||x.type===$('filter').value).slice().sort((a,b)=>b.date.localeCompare(a.date));for(const x of records){const card=document.createElement('div');card.className='history-card';row(card,x.type+' · '+workoutText(x),`${x.date} · RPE ${x.rpe}${x.note?' · '+x.note:''}`,[['수정',()=>editWorkout(x)],['삭제',()=>{if(confirm('이 훈련을 삭제할까요?')){state.workouts=state.workouts.filter(y=>y.id!==x.id);persist();render();}}]]);$('workouts').append(card);}if(!records.length)$('workouts').textContent='기록을 추가하면 훈련 흐름이 여기에 표시됩니다.';$('pbList').replaceChildren();for(const [k,label] of Object.entries(pbLabels)){const pb=state.pbs[k];row($('pbList'),label,pb?`${k==='erg30'?pb.meters+'m':fmtTime(pb.seconds)} · ${pb.date}`:'미등록',pb?[['삭제',()=>{if(confirm('PB를 삭제할까요?')){delete state.pbs[k];persist();render();}}]]:[]);}$('events').replaceChildren();for(const e of state.events.slice().sort((a,b)=>a.date.localeCompare(b.date))){const card=document.createElement('div');card.className='history-card';row(card,e.name,`${e.date} · ${dday(e.date)} · ${e.boat||''} · ${e.goal||''}`,[['삭제',()=>{if(confirm('대회를 삭제할까요?')){state.events=state.events.filter(x=>x.id!==e.id);persist();render();}}]]);$('events').append(card);}if(!state.events.length)$('events').textContent='다음 대회를 등록하세요.';renderContext();}
function autoPb(v){const key=v.type==='에르고'&&[2000,5000].includes(v.distance)?'erg'+v.distance:v.type==='러닝'&&[5,8].includes(v.distance)?'run'+v.distance*1000:null;if(key&&(!state.pbs[key]||v.time<state.pbs[key].seconds))state.pbs[key]={seconds:v.time,date:v.date};}
function cancelEdit(){$('editId').value='';$('saveWorkout').textContent='훈련 저장';$('cancelEdit').hidden=true;$('note').value='';renderFields();}
function editWorkout(x){showPage('training');$('type').value=x.type;renderFields();$('date').value=x.date;$('rpe').value=x.rpe;$('rpeOut').textContent=x.rpe;$('note').value=x.note||'';$('editId').value=x.id;$('saveWorkout').textContent='수정 저장';$('cancelEdit').hidden=false;for(const [id] of fields[x.type])if(x[id]!=null)$('f_'+id).value=x[id];if(x.type==='웨이트')$('f_exercise').value=x.exercise||'';if(x.time)setTime('f_',x.time);}
$('workoutForm').onsubmit=e=>{e.preventDefault();const type=$('type').value,date=$('date').value;if(!validDate(date)||date>today())return toast('오늘 이전의 유효한 날짜를 선택하세요.');const v={id:$('editId').value||crypto.randomUUID(),date,type,rpe:Number($('rpe').value),note:$('note').value.trim()};for(const [id] of fields[type])if($('f_'+id).value!=='')v[id]=Number($('f_'+id).value);if(type==='웨이트')v.exercise=$('f_exercise').value.trim();if(['에르고','러닝'].includes(type)){v.time=seconds('f_');if(v.time<=0)return toast('기록 시간은 0초보다 커야 합니다.');}const idx=state.workouts.findIndex(x=>x.id===v.id);if(idx>=0)state.workouts[idx]=v;else state.workouts.push(v);autoPb(v);if(persist()){toast('훈련을 저장했습니다.');cancelEdit();render();}};
$('cancelEdit').onclick=cancelEdit;$('type').onchange=()=>{cancelEdit();};$('filter').onchange=render;
$('checkinForm').onsubmit=e=>{e.preventDefault();state.checkins[today()]={condition:Number($('condition').value),sleep:Number($('sleep').value),fatigue:Number($('fatigue').value),note:$('checkNote').value.trim()};if(persist()){render();toast('오늘의 체크인을 저장했습니다.');}};
for(const id of ['condition','rpe'])$(id).oninput=()=>$(id+'Out').textContent=$(id).value;
$('profileForm').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));for(const k of ['age','height','weight','experience'])p[k]=p[k]===''?null:Number(p[k]);state.profile=p;if(persist()){render();toast('프로필을 저장했습니다.');}};
for(const [k,v] of Object.entries(state.profile)){const field=$('profileForm').elements.namedItem(k);if(field)field.value=v??'';}
$('goalText').value=state.goals;$('goalForm').onsubmit=e=>{e.preventDefault();state.goals=$('goalText').value.trim();if(persist()){renderContext();toast('목표를 저장했습니다.');}};
$('pbType').onchange=pbFields;$('pbForm').onsubmit=e=>{e.preventDefault();const k=$('pbType').value,value=k==='erg30'?Number($('pbMeters').value):seconds('pb');if(value<=0)return toast('0보다 큰 기록을 입력하세요.');const old=state.pbs[k];if(old&&(k==='erg30'?value<=old.meters:value>=old.seconds)&&!confirm('기존 PB를 이 기록으로 정정할까요?'))return;state.pbs[k]={date:today(),[k==='erg30'?'meters':'seconds']:value};if(persist()){render();toast('PB를 저장했습니다.');}};
$('eventForm').onsubmit=e=>{e.preventDefault();const date=$('eventDate').value;if(!validDate(date))return toast('시합 날짜를 확인하세요.');state.events.push({id:crypto.randomUUID(),date,name:$('eventName').value.trim(),boat:$('eventBoat').value.trim(),goal:$('eventGoal').value.trim()});if(persist()){e.target.reset();render();toast('대회를 등록했습니다.');}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));for(const m of ['chat','week','photo'])$(m+'Panel').hidden=m!==b.dataset.mode;if(b.dataset.mode==='week')$('weekFacts').textContent=weeklyReport(getContext());});
function bubble(text,role){const el=document.createElement('div');el.className='bubble '+role;el.textContent=text;$('messages').append(el);el.scrollIntoView({block:'nearest'});return el;}
function engineProgress(p){$('engineMessage').textContent=p.message;const bar=$('engineBar');if(Number.isFinite(p.progress))bar.value=Math.min(100,p.progress);else bar.removeAttribute('value');}
async function requestAnalysis(mode,question='',image=null,onToken=null){
  if(busy)throw Error('현재 요청이 끝난 뒤 다시 시도하세요.');
  busy=true;const buttons=document.querySelectorAll('#coach button.primary, #visionPhoto, #newChat');buttons.forEach(x=>x.disabled=true);
  $('engineProgress').hidden=false;$('aiStatus').textContent='무료 기기 처리 중 · API 비용 0원';engineProgress({message:'기기 모델 준비 중'});
  let timer;
  const stopped=new Promise((_,reject)=>{cancelRequest=reject;timer=setTimeout(()=>{freeAI.cancel();reject(Error('처리가 오래 걸려 중지했습니다. Wi-Fi에서 다시 시도하세요. 유료 API는 호출하지 않았습니다.'));},600000);});
  try{
    const task=mode==='ocr'?freeAI.recognize(image,engineProgress):freeAI.generate({mode,question,image,context:getContext(),history:mode==='chat'?history:[]},engineProgress,onToken);
    const data=await Promise.race([task,stopped]);
    if(mode==='ocr')$('aiStatus').textContent='실제 사진 문자인식 완료 · 무료';
    else{if(!data.analysis||!data.responseId||!data.provider.startsWith('local'))throw Error('기기 모델의 실제 응답을 확인하지 못했습니다.');$('aiStatus').textContent='실제 기기 AI 응답 · '+data.model.split('/').at(-1);}
    return data;
  }catch(error){$('aiStatus').textContent='기기 처리 중지·실패 · 유료 호출 없음';throw error;}
  finally{clearTimeout(timer);cancelRequest=null;busy=false;$('engineProgress').hidden=true;buttons.forEach(x=>x.disabled=false);}
}
$('cancelAI').onclick=()=>{freeAI.cancel();cancelRequest?.(Error('요청을 중지했습니다. 다시 시도할 수 있습니다.'));};
$('newChat').onclick=()=>{history=[];$('messages').replaceChildren();bubble('새 대화를 시작했습니다. 현재 선수 기록은 계속 참고합니다.','assistant');};
$('chatForm').onsubmit=async e=>{e.preventDefault();const q=$('question').value.trim();if(!q||busy)return;bubble(q,'user');const pending=bubble('무료 기기 AI 준비 중…','assistant');try{const d=await requestAnalysis('chat',q,null,text=>pending.textContent='기기 AI 생성 중…\n'+text);pending.textContent='무료 기기 AI · Qwen2.5\n'+d.analysis;history.push({role:'user',content:q},{role:'assistant',content:d.analysis});history=history.slice(-8);$('question').value='';}catch(err){pending.textContent=err.message;pending.classList.add('error');}};
async function analyze(mode,id,image=null){const result=$(id);result.classList.remove('error');result.textContent='무료 기기 AI 준비 중…';try{const d=await requestAnalysis(mode,'',image,text=>result.textContent='기기 AI 생성 중…\n'+text);result.textContent=(mode==='photo'?'무료 사진 AI · 숫자를 화면과 대조하세요\n':'무료 기기 AI 해석\n')+d.analysis;}catch(e){result.classList.add('error');result.textContent=e.message;}}
$('calculateWeek').onclick=()=>{$('weekFacts').textContent=weeklyReport(getContext());};
$('analyzeWeek').onclick=()=>analyze('week','weekResult');
async function imageData(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('15MB 이하 JPG·PNG·WebP 사진을 선택하세요.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',.85);if(data.length>2800000)throw Error('사진이 너무 큽니다. 기록 화면만 잘라 다시 선택하세요.');return data;}
$('ergPhoto').onchange=async()=>{photo=null;$('photoSaveForm').hidden=true;$('photoResult').textContent='';$('visionResult').textContent='';const file=$('ergPhoto').files[0];if(!file)return;try{photo=await imageData(file);if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);$('preview').src=previewURL;$('preview').hidden=false;}catch(e){$('preview').hidden=true;$('photoResult').textContent=e.message;}};
$('analyzePhoto').onclick=async()=>{
  if(!photo)return toast('인식할 사진을 먼저 선택하세요.');
  const out=$('photoResult');out.classList.remove('error');out.textContent='실제 사진 글자를 읽는 중…';
  try{const data=await requestAnalysis('ocr','',photo);const {result,report}=monitorReport(data.text,data.confidence);out.textContent=report;
    $('photoDate').value=today();$('photoDate').max=today();$('photoDistance').value=result.distance||'';$('photoMin').value=result.time?Math.floor(result.time/60):'';$('photoSec').value=result.time?+(result.time%60).toFixed(1):'';$('photoStroke').value=result.stroke&&result.stroke<=60?result.stroke:'';$('photoSaveForm').hidden=false;
  }catch(error){out.classList.add('error');out.textContent=error.message;}
};
$('visionPhoto').onclick=()=>{if(!photo)return toast('사진을 먼저 선택하세요.');analyze('photo','visionResult',photo);};
$('photoSaveForm').onsubmit=e=>{
  e.preventDefault();const date=$('photoDate').value,time=Number($('photoMin').value)*60+Number($('photoSec').value);
  if(!validDate(date)||date>today()||time<=0)return toast('날짜와 0초보다 큰 시간을 확인하세요.');
  const v={id:crypto.randomUUID(),date,type:'에르고',distance:Number($('photoDistance').value),time,rpe:Number($('photoRpe').value),note:'Concept2 사진 · 선수 확인 후 저장'};
  if($('photoStroke').value)v.stroke=Number($('photoStroke').value);
  state.workouts.push(v);autoPb(v);if(persist()){render();$('photoSaveForm').hidden=true;toast('확인한 사진 기록을 저장했습니다.');}
};
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:3,...state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='athletix-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('importData').onchange=async()=>{try{const file=$('importData').files[0];if(!file)return;if(file.size>5000000)throw Error('백업 파일이 너무 큽니다.');const data=JSON.parse(await file.text());if(data.version!==3||!Array.isArray(data.workouts)||!Array.isArray(data.events)||typeof data.goals!=='string'||!data.profile||!data.pbs||!data.checkins||Array.isArray(data.profile)||Array.isArray(data.pbs)||Array.isArray(data.checkins)||data.workouts.some(x=>!x||typeof x.id!=='string'||!validDate(x.date)||!fields[x.type])||data.events.some(x=>!x||!validDate(x.date)||typeof x.name!=='string'))throw Error('유효한 ATHLETIX V3 백업이 아닙니다.');if(!confirm('현재 데이터를 백업 파일로 교체할까요?'))return;for(const k of Object.keys(keys))state[k]=data[k];if(persist())location.reload();}catch(e){toast(e.message);}};
if(!localStorage.getItem('athMigrated')){const old=read('workouts',[]);if(Array.isArray(old))state.workouts.push(...old.map(x=>({id:crypto.randomUUID(),date:today(),type:fields[x.type]?x.type:'에르고',legacy:x.result||'',rpe:Number(x.rpe)||7})));if(persist())localStorage.setItem('athMigrated','1');}
$('date').value=today();$('date').max=today();renderFields();pbFields();render();
