const $=id=>document.getElementById(id);
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const state={workouts:read('athWorkouts',[]),checkins:read('athCheckins',{}),pbs:read('athPbs',{}),events:read('athEvents',[])};
// Import records from the original single-file version once.
if(!localStorage.getItem('athMigrated')){const old=read('workouts',[]);if(Array.isArray(old))state.workouts.push(...old.map(x=>({id:crypto.randomUUID(),date:today(),type:x.type||'에르고',legacy:x.result||'',rpe:Number(x.rpe)||7})));const oldPb=localStorage.getItem('pb');if(oldPb&&/^\d+:\d{2}(\.\d)?$/.test(oldPb))state.pbs.erg2000={seconds:parseTime(oldPb),date:today()};localStorage.setItem('athMigrated','1');persist()}
function persist(){for(const [key,value] of Object.entries({athWorkouts:state.workouts,athCheckins:state.checkins,athPbs:state.pbs,athEvents:state.events}))localStorage.setItem(key,JSON.stringify(value))}
function parseTime(s){const m=/^(\d+):([0-5]\d)(?:\.(\d))?$/.exec(s);return m?Number(m[1])*60+Number(m[2])+Number('0.'+(m[3]||0)):NaN}
function fmtTime(s){if(!Number.isFinite(s))return '—';let min=Math.floor(s/60),sec=(s-min*60).toFixed(1);if(Number(sec)>=60){min++;sec='0.0'}return min+':'+sec.padStart(4,'0')}
function num(id,min=0){const input=$(id),v=Number(input.value);return input.value!==''&&Number.isFinite(v)&&v>min&&input.checkValidity()?v:null}
const fields={
 '수상':[['distance','거리 (km)','number','0.1','0.01'],['minutes','시간 (분)','number','0.1','0.1'],['stroke','평균 피치 (선택)','number','1','1']],
 '에르고':[['distance','거리 (m)','number','1','1'],['time','시간 (분:초.초)','text','예: 6:44.0'],['stroke','평균 피치 (선택)','number','1','1']],
 '웨이트':[['exercise','운동 이름','text','예: 스쿼트'],['weight','중량 (kg)','number','0','0.5'],['sets','세트','number','1','1'],['reps','반복 횟수','number','1','1']],
 '러닝':[['distance','거리 (km)','number','0.1','0.01'],['time','시간 (분:초.초)','text','예: 23:00']]
};
function renderFields(){const type=$('type').value;$('fields').replaceChildren();for(const [id,title,kind,min,step] of fields[type]){const label=document.createElement('label');label.textContent=title;const input=document.createElement('input');input.id='f_'+id;input.type=kind;input.inputMode=kind==='number'?'decimal':'text';input.placeholder=kind==='text'?min:'';if(kind==='number'){input.min=min;input.step=step}label.append(input);$('fields').append(label)}}
const pbLabels={erg2000:'에르고 2,000m',erg5000:'에르고 5,000m',erg30:'에르고 30분 거리',run5000:'러닝 5km',run8000:'러닝 8km'};
function renderPbField(){const distance=$('pbType').value==='erg30';$('pbFields').innerHTML=distance?'<label>거리 (m)<input id="pbValue" type="number" min="1" step="1" inputmode="numeric" placeholder="예: 7800"></label>':'<label>기록 (분:초.초)<input id="pbValue" inputmode="decimal" placeholder="예: 6:37.5"></label>'}
function weekStart(){const d=new Date(today()+'T00:00:00');d.setDate(d.getDate()-6);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function formatWorkout(x){if(x.legacy)return x.legacy;if(x.type==='웨이트')return [x.exercise,x.weight+'kg',x.sets+'×'+x.reps].join(' · ');return (x.distance||0)+(x.type==='에르고'?'m':'km')+(x.time?' · '+fmtTime(x.time):x.minutes?' · '+x.minutes+'분':'')+(x.stroke?' · 피치 '+x.stroke:'')}
function dday(date){const diff=Math.round((Date.parse(date+'T00:00:00')-Date.parse(today()+'T00:00:00'))/86400000);return diff===0?'D-DAY':diff>0?'D-'+diff:'D+'+(-diff)}
function row(parent,primary,secondary,id,remove){const div=document.createElement('div');div.className='row';const text=document.createElement('span');text.textContent=primary;const small=document.createElement('small');small.textContent=secondary;text.append(small);div.append(text);if(remove){const b=document.createElement('button');b.className='delete';b.textContent='삭제';b.setAttribute('aria-label',primary+' 삭제');b.onclick=()=>{remove(id);persist();render()};div.append(b)}parent.append(div)}
function render(){const t=today(),start=weekStart(),c=state.checkins[t];$('homeCondition').textContent=c?.condition??'—';$('condition').value=c?.condition??7;$('conditionOut').textContent=$('condition').value;$('sleep').value=c?.sleep??'';$('homePb').textContent=state.pbs.erg2000?fmtTime(state.pbs.erg2000.seconds):'—';const upcoming=state.events.filter(x=>x.date>=t).sort((a,b)=>a.date.localeCompare(b.date));$('homeDday').textContent=upcoming.length?dday(upcoming[0].date):'대회 등록';$('homeEvent').textContent=upcoming[0]?.name||'날짜를 설정해 주세요';const week=state.workouts.filter(x=>x.date>=start&&x.date<=t),checks=Object.entries(state.checkins).filter(([date])=>date>=start&&date<=t);$('weekStats').textContent=week.length+'회 훈련 · 평균 RPE '+(week.length?(week.reduce((s,x)=>s+Number(x.rpe),0)/week.length).toFixed(1):'—')+' · 체크인 '+checks.length+'일';$('workouts').replaceChildren();for(const x of state.workouts.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30))row($('workouts'),x.type+' · '+formatWorkout(x),x.date+' · RPE '+x.rpe,x.id,id=>state.workouts=state.workouts.filter(y=>y.id!==id));if(!state.workouts.length)$('workouts').textContent='아직 기록이 없습니다.';$('pbList').replaceChildren();for(const [key,label] of Object.entries(pbLabels)){const value=state.pbs[key];row($('pbList'),label,value?(key==='erg30'?value.meters+'m':fmtTime(value.seconds))+' · '+value.date:'미등록',key,id=>delete state.pbs[id])}$('events').replaceChildren();for(const e of upcoming)row($('events'),e.name,e.date+' · '+dday(e.date),e.id,id=>state.events=state.events.filter(x=>x.id!==id));if(!upcoming.length)$('events').textContent='예정된 대회가 없습니다.'}
function saveWorkout(){const type=$('type').value,date=$('date').value;if(!date||date>today())return alert('유효한 훈련 날짜를 입력해 주세요.');const v={id:crypto.randomUUID(),date,type,rpe:Number($('rpe').value),note:$('note').value.trim()};for(const [id,,,min] of fields[type]){const input=$('f_'+id);if(!input.value.trim()){if(id==='stroke')continue;return alert('필수 항목을 입력해 주세요.')}if(id==='time'){v.time=parseTime(input.value.trim());if(!Number.isFinite(v.time)||v.time<=0)return alert('시간은 분:초 형식으로 입력해 주세요.')}else if(id==='exercise'){v.exercise=input.value.trim().slice(0,60)}else{const n=Number(input.value);if(!input.checkValidity()||!Number.isFinite(n)||n<Number(min)||((id==='distance'||id==='minutes'||id==='weight')&&n<=0))return alert('숫자 입력을 확인해 주세요.');v[id]=n}}
state.workouts.push(v);if(type==='에르고'&&[2000,5000].includes(v.distance)){const key='erg'+v.distance;if(!state.pbs[key]||v.time<state.pbs[key].seconds)state.pbs[key]={seconds:v.time,date}}if(type==='러닝'&&[5,8].includes(v.distance)){const key='run'+v.distance*1000;if(!state.pbs[key]||v.time<state.pbs[key].seconds)state.pbs[key]={seconds:v.time,date}}persist();render();renderFields();$('note').value='';alert('훈련을 저장했습니다.')}
function savePb(){const key=$('pbType').value,raw=$('pbValue').value.trim(),distance=key==='erg30';const value=distance?Number(raw):parseTime(raw);if(!raw||!Number.isFinite(value)||value<=0||(distance&&(!Number.isInteger(value)||value>20000)))return alert(distance?'거리(m)를 확인해 주세요.':'기록은 분:초 형식으로 입력해 주세요.');const old=state.pbs[key];if(old&&(distance?value<=old.meters:value>=old.seconds))return alert('기존 PB보다 좋은 기록만 저장할 수 있습니다.');state.pbs[key]={date:today(),[distance?'meters':'seconds']:value};persist();render();$('pbValue').value=''}
function saveEvent(){const name=$('eventName').value.trim(),date=$('eventDate').value;if(!name||!date||date<today())return alert('대회명과 오늘 이후 날짜를 입력해 주세요.');state.events.push({id:crypto.randomUUID(),name,date});persist();render();$('eventName').value='';$('eventDate').value=''}
async function requestAnalysis(payload,id,button){button.disabled=true;$(id).textContent='분석 중…';try{const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'분석 요청에 실패했습니다.');$(id).textContent=data.analysis||'분석 결과가 없습니다.'}catch(e){$(id).textContent=e.message}finally{button.disabled=false}}
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('사진을 읽지 못했습니다.'));reader.readAsDataURL(file)})}
$('saveCheckin').onclick=()=>{const sleep=$('sleep').value;if(sleep!==''&&(!$('sleep').checkValidity()||Number(sleep)>24))return alert('수면 시간을 확인해 주세요.');state.checkins[today()]={condition:Number($('condition').value),sleep:sleep===''?null:Number(sleep)};persist();render();alert('체크인을 저장했습니다.')};
$('saveWorkout').onclick=saveWorkout;$('savePb').onclick=savePb;$('saveEvent').onclick=saveEvent;$('type').onchange=renderFields;$('pbType').onchange=renderPbField;
for(const id of ['condition','rpe'])$(id).oninput=()=>$(id==='rpe'?'rpeOut':'conditionOut').textContent=$(id).value;
document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.toggle('on',p.id===button.dataset.page));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.page===button.dataset.page));scrollTo(0,0)});
$('analyzeWeek').onclick=()=>{const start=weekStart(),workouts=state.workouts.filter(x=>x.date>=start&&x.date<=today());if(!workouts.length){$('weekResult').textContent='최근 7일 훈련 기록이 없습니다.';return}requestAnalysis({mode:'week',workouts,checkins:Object.entries(state.checkins).filter(([date])=>date>=start&&date<=today())},'weekResult',$('analyzeWeek'))};
$('ergPhoto').onchange=()=>{const file=$('ergPhoto').files[0];if(!file)return;const url=URL.createObjectURL(file);$('preview').src=url;$('preview').hidden=false;$('preview').onload=()=>URL.revokeObjectURL(url)};
$('analyzePhoto').onclick=async()=>{const file=$('ergPhoto').files[0];if(!file)return alert('사진을 선택해 주세요.');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>4*1024*1024)return alert('JPG, PNG, WebP 사진을 4MB 이하로 선택해 주세요.');const button=$('analyzePhoto');try{const image=await fileData(file);await requestAnalysis({mode:'photo',image},'photoResult',button)}catch(e){$('photoResult').textContent=e.message}};
$('date').value=today();renderFields();renderPbField();render();
